<<<<<<< HEAD
server.port=8080
logging.level.org.zalando.logbook=TRACE
=======
logging.level.ru.yandex.practicum=debug
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
>>>>>>> b13c2dd (Произведен рефакторинг кода: 1. Исправлены валидаторы в POJO (заменены на аннотации), также согласно условию ТЗ добавлены новые сущности + реализована работа с БД Н2. Изменена структура дирректорий проекта. Добавлены новые интерфейсы и контроллеры. Добавлены DAO классы (реализующие новые интерфейсы). Приложение проверено через Postman. Все тесты пройдены успешно.)
